# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25543f675923e3df07e6a5032306dad8f8352b9bea757ebd343ec263a3821d4a6470df9853dc30770e0312c796a3a584e3b08c429977d4ddef68d91af3030a65
  host_url: 'http://localhost:3000'

test:
  secret_key_base: 86f704af79e9acccc1c41a53d9583b7b6044866ce12f7de37d2a2427797b36c0559de47e34900194482e2df9fdfc646ee2b683b7d5c3fe778d1ba89d6ebccf51
  host_url: 'http://localhost:3000'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  host_url: 'https://beacon.com'
